name: Auto Pull Request

on:
  push:
    branches-ignore:
    - main
    - dev
    - hotfix/**
    - bugfix/**
    - release/**

jobs:
  autopr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: autopr
      id: autopr
      uses: devops-infra/action-pull-request@v0.5.0
      with:
        github_token: ${{ github.token }}
        target_branch: dev
        title: '[create-pull-request] automated change'
        body: '[create-pull-request] automated change'
        reviewer: Dev0psPleb
        label: |
          autopr
        milestone: My milestone
        draft: true
        old_string: "<!-- Add your description here -->"
        new_string: "** Automatic pull request**"
        get_diff: true
        ignore_users: "dependabot"
        allow_no_diff: false
