name: Auto Pull Request

on:
  push:
    branches-ignore:
    - main
    - dev
    - hotfix/**
    - bugfix/**
    - release/**

jobs:
  autopr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: autopr
      id: autopr
      uses: peter-evans/create-pull-request@v4
      with:
        base: dev
        token: ${{ github.token }}

