name: Auto Pull Request

on:
  push:
    branches:
    - feature/**
    branches-ignore:
    - main
    - dev

jobs:
  autopr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: dev
    - name: autopr
      id: autopr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ github.token }}
        delete-branch: false
        labels: |
          autopr
          feature
        reviewers: Dev0psPleb
