name: Terraform Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Terraform Lint
      uses: ${{ github.action_repository }}/.github/actions/terraform_lint@${{ github.ref }}
