name: Terraform Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Lint
      id: lint
      continue-on-error: true
      run: |
        terraform fmt -check -recursive -diff
    - id: diff
      run: |
        echo '${{ steps.lint.outputs.stdout || steps.lint.outputs.stderr }}' \
        | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > diff.txt
    - name: Put diff in Env Var
      run: |
        DIFF=$(cat diff.txt)
        echo "DIFF<<EOF" >> $GITHUB_ENV
        echo "$DIFF" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
